### ISSUE TITLE
询问vsixinstaller extension

### ISSUE THREAD

**Issue by wentata** [lovelyyoshino/Halcon_licenses#12]
请问版主有steady版本 visual studio 2022 halcon variable inspect extension 的 installer 吗？

**Comment by lovelyyoshino** [comment]
抱歉，没有这个版本，有可能您需要购买正版软件而不是试用

**Comment by lovelyyoshino** [comment]
> 4104

你好，这个首先需要检查你的batch size是否满足要求，然后检查你的数据是否使用CPU读取的
