### ISSUE TITLE
Can you please update the new license again? 

### ISSUE THREAD

**Issue by AdimasBarelang** [lovelyyoshino/Halcon_licenses#14]
I tried to contact you by e-mail, but I was afraid that you wouldn't respond. So I created a new issue here.

**Comment by JPadraoSil** [comment]
There you go. Don't ask where I found them.
[2023-09.zip](https://github.com/lovelyyoshino/Halcon_licenses/files/12511947/2023-09.zip)

**Comment by lovelyyoshino** [comment]
Updated, recently on a business trip, did not check email

**Comment by JPadraoSil** [comment]
> @JPadraoSil If you are willing, you can maintain this project together and look forward to your reply

I don't use GitHub very often but since I need the licenses to work, I can take care of the issues that pop up asking for them if I have them.
