### ISSUE TITLE
Most recent license not updated

### ISSUE THREAD

**Issue by kadjay00** [lovelyyoshino/Halcon_licenses#2]
folder 2021.06 contains license_support_halcon12_2020_06.dat.
This is from last year thus the license is expired and does not work

**Comment by lovelyyoshino** [comment]
ok, I have updated

**Comment by kadjay00** [comment]
Hi Yoshino,

Do you happen to have a new demo license for Halcon 12.0?
Or where do you apply for those licenses? Then I can also do it myself

Kind regards,

Erik

Op ma 14 jun. 2021 om 14:38 schreef lovelyyoshino ***@***.***

**Comment by songsh72** [comment]
Hi Yoshino,
I also need Halcon 12.0.
Is it possible to update?
Song
