### ISSUE TITLE
Upload october 2024 Eval License

### ISSUE THREAD

**Issue by Imperare** [lovelyyoshino/Halcon_licenses#25]
Anyone could upload October 2024 Evaluation License please ? Thanks in Advance.

**Comment by ikeriparraguirre** [comment]
Take it.
[2024-10.zip](https://github.com/user-attachments/files/17221667/2024-10.zip)

**Comment by Imperare** [comment]
Thank you so much

**Comment by Imperare** [comment]
Hm. For every people who use eval halcon progress, the last license doesn't work for me.

**Comment by ikeriparraguirre** [comment]
Hi, I use Halcon 13 and the licence I sent you works fine for me.

**Comment by Imperare** [comment]
Thanks for your feedback. I use Halcon 23.05 and put license_eval_halcon_progress_2024_10.dat on my %HALCONROOT%\license folder like I have been doing for a year.

But I can see "Version applicable: [23.11P], [24.05P], 24.11P/S" so maybe should I install 24.05.

**Comment by ikeriparraguirre** [comment]
It could be that, I search on the internet and it says that the error is probably an incompatibility between the modules. This error is not related to the licenses.
Every month when I download the licenses I copy all to the license folder. I would do the same, instead of copying only license_eval_halcon_progress_2024_10.dat

**Comment by Imperare** [comment]
I copied all licenses but get the same error... I will look on my side, thanks again for sharing.

**Comment by ikeriparraguirre** [comment]
That error has never appeared to me, so I can't help you any more.

**Comment by Imperare** [comment]
License works with 24.05.

**Comment by ikeriparraguirre** [comment]
Perfect!

**Comment by lovelyyoshino** [comment]
Got it
