### ISSUE TITLE
Folder name on the wrong format

### ISSUE THREAD

**Issue by psavard** [lovelyyoshino/Halcon_licenses#27]
Is it possible to rename the November folder to the same format as usual (2024.11)?

thank you very much.

Pierre-Yves Savard

**Comment by ikeriparraguirre** [comment]
Hi psavard,
I have just created a pull request with your request.
Now we will have to wait for lovelyyoshino to accept the changes.
Pull request link: https://github.com/lovelyyoshino/Halcon_licenses/pull/28
