### ISSUE TITLE
Halcon 22.05 Progress License

### ISSUE THREAD

**Issue by adrianfernandeziturcemi** [lovelyyoshino/Halcon_licenses#29]
Greetings, 

I am trying to activate the license i need for an specific version of HALCON -> 22.05 PROGRESS but none of the current (november 2024 licenses) seems to work, could you update the repo pls ?

**Comment by lovelyyoshino** [comment]
pls give me pic to show

**Comment by adrianfernandeziturcemi** [comment]
> pls give me pic to show

What picture do you need?, the Halcon Error?
