### ISSUE TITLE
不太了解怎麼弄license

### ISSUE THREAD

**Issue by shawn846520** [lovelyyoshino/Halcon_licenses#3]
我的版本是HDevelop 20.11 Progress - MVTec HALCON
但是把您發佈上去的license複製下來，並建立一個文字檔貼到文字檔裡，然後把檔名改成license.dat或是您發佈的檔名
(例如 license_support_halcon20.11_steady-dl_2021_08.dat)，
他還是會跳出21010這個錯誤訊息。
由於螢幕錄製的影片容量大小超過限制，因此MAIL給您。 
謝謝

**Comment by lovelyyoshino** [comment]
您应该选择这个版本的进行注册，因为您是Progress 版本，如果无效请下载21.09版本
![image](https://user-images.githubusercontent.com/21984530/128185797-5c14ae4f-ba7a-4151-9d3a-975c33ff618a.png)
