### ISSUE TITLE
can not work in MVTec HDevelop XL 22.11 Steady (user)

### ISSUE THREAD

**Issue by ZhuJD-China** [lovelyyoshino/Halcon_licenses#31]

**Comment by lovelyyoshino** [comment]
do you mean halcon 22.11 is not useful？maybe you can try license_support_halcon_progress_2024_12.dat

**Comment by Delphi4Ever** [comment]
You cannot use anymore those licenses for old HDEVELOPs, only for new ones. They works only for demo in runtimes environments.

**Comment by lovelyyoshino** [comment]
You cannot use anymore those licenses for old HDEVELOPs, only for new ones. They works only for demo in runtimes environments.

**Comment by lovelyyoshino** [comment]
Only 24.05, 24.11, not listed versions are no longer supported
