### ISSUE TITLE
Halcon License Steady Evaluation December 2024

### ISSUE THREAD

**Issue by automataHG** [lovelyyoshino/Halcon_licenses#32]
Can you please upload the Steady evaluation version from December 2024?

thanks,

**Comment by lovelyyoshino** [comment]
I also obtained it through the official channel, now the official does not support the version below 24, you can see my readme content

**Comment by automataHG** [comment]
Sorry but you said that the halcon evaluation license for Steady version 22 is not more available?

**Comment by lovelyyoshino** [comment]
If you want you can buy the official version or cracked version, the learning version only supports halcon24
