### ISSUE TITLE
Error 21010

### ISSUE THREAD

**Issue by wentata** [lovelyyoshino/Halcon_licenses#5]
![Untitled](https://user-images.githubusercontent.com/30208646/148005383-1dfb22b3-63aa-49b0-be29-461097d63828.png)

21010报错，请问该怎么检查
我的版本是steady 20.11.1.1

**Comment by wentata** [comment]
![Untitled](https://user-images.githubusercontent.com/30208646/148005508-4bd77e11-bdd5-4f6f-8693-9c9f9e60ca26.png)
之前两个月没有类似的问题

**Comment by wentata** [comment]
I try to open it today 05/01/22 and it works now, seems like the problem should be came from the time or time zone. 
I will close the issues and thanks for the license :)

**Comment by lovelyyoshino** [comment]
Well, I'm glad you solved the problem by yourself.
